"""
db/orm_models.py
----------------
SQLAlchemy ORM models — the database table definitions.

Why this exists:
    Defines the shape of every table in the FlightHacker database using
    SQLAlchemy's mapped_column() API. These are NOT the same as the Pydantic
    models in models/ — ORM models describe the database structure, Pydantic
    models describe API request/response shapes.

What it connects to:
    - db/base.py: all models inherit from Base
    - db/session.py: imports this module so tables are registered at startup
    - repositories/: repository classes query these models
    - Alembic: reads these models to generate migration scripts

Table overview:
    users           — one row per registered user (Clerk user ID as PK)
    saved_searches  — searches the user has bookmarked for price tracking
    price_history   — every flight query result, used to detect anomalies
    alert_rules     — price alert conditions set by users
"""

from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from db.base import Base


class User(Base):
    """
    One row per FlightHacker user.

    user_id is the Clerk user ID (format: "user_abc123"). Used as the primary
    key so we never need an additional ID layer — Clerk is the source of truth
    for identity.

    avios_balance and pence_per_point are stored here as user preferences.
    Both are optional — users who don't use Avios simply leave them null.
    """

    __tablename__ = "users"

    # Clerk user ID — primary key, never auto-generated by us.
    user_id: Mapped[str] = mapped_column(String(64), primary_key=True)

    # Email — stored for notification delivery. Synced from Clerk.
    email: Mapped[str | None] = mapped_column(String(256), nullable=True)

    # Avios / loyalty points balance. Null = user hasn't set this up yet.
    avios_balance: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # How much the user values 1 Avios point in pence.
    # Default 1.0 = 1p per Avios (industry standard baseline).
    pence_per_point: Mapped[float] = mapped_column(Float, default=1.0)

    # ntfy topic for this user's push notifications.
    # Generated on first sign-up: "flighthacker-{user_id}".
    # User subscribes to this topic in the ntfy app.
    ntfy_topic: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # Subscription status. RevenueCat webhooks update this field.
    # Values: "trialing" | "active" | "cancelled" | "expired"
    subscription_status: Mapped[str] = mapped_column(String(32), default="trialing")

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships — one user has many searches and alerts
    saved_searches: Mapped[list["SavedSearch"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    alert_rules: Mapped[list["AlertRule"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class SavedSearch(Base):
    """
    A route search the user has saved for ongoing price monitoring.

    Stored so the app can re-run the search periodically and compare
    results against price history to detect drops.

    Max 20 per user (enforced in the API layer, not here).
    """

    __tablename__ = "saved_searches"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to the user who saved this search.
    user_id: Mapped[str] = mapped_column(String(64), ForeignKey("users.user_id"))

    # IATA code of origin city/airport (e.g. "LHR" or "LON")
    origin: Mapped[str] = mapped_column(String(8))

    # IATA code of destination city/airport (e.g. "NRT" or "TYO")
    destination: Mapped[str] = mapped_column(String(8))

    # Preferred travel dates stored as ISO strings (flexible ranges allowed)
    travel_date: Mapped[str | None] = mapped_column(String(32), nullable=True)
    return_date: Mapped[str | None] = mapped_column(String(32), nullable=True)

    # Last known best price in GBP. Updated on each re-run.
    last_price_gbp: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship(back_populates="saved_searches")
    alert_rules: Mapped[list["AlertRule"]] = relationship(
        back_populates="saved_search", cascade="all, delete-orphan"
    )


class PriceHistory(Base):
    """
    Every flight query result ever seen by the app.

    Why we store everything: this is how the app builds its own price baseline
    without paying for a historical data service. After a few months, this
    table tells us what a 'normal' price is for any route — enabling accurate
    anomaly detection for error fares and price drops.

    High write volume expected. Index on (origin, destination, travel_date)
    for fast lookups during anomaly detection.
    """

    __tablename__ = "price_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    origin: Mapped[str] = mapped_column(String(8), index=True)
    destination: Mapped[str] = mapped_column(String(8), index=True)
    travel_date: Mapped[str] = mapped_column(String(16), index=True)

    # Price in GBP (already converted from USD at storage time)
    price_gbp: Mapped[float] = mapped_column(Float)

    # Which airline operated this price
    airline: Mapped[str | None] = mapped_column(String(8), nullable=True)

    # Which hacking method found this result
    # e.g. "direct", "hub_istanbul", "open_jaw", "positioning_paris"
    method: Mapped[str | None] = mapped_column(String(64), nullable=True)

    observed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )


class AlertRule(Base):
    """
    A price alert condition set by a user.

    When the Celery worker re-runs a saved search, it checks all active
    alert rules for that search. If conditions are met, it sends a push
    notification via ntfy.

    Max 10 per user (enforced in the API layer).
    """

    __tablename__ = "alert_rules"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    user_id: Mapped[str] = mapped_column(String(64), ForeignKey("users.user_id"))
    saved_search_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("saved_searches.id")
    )

    # Trigger type: "target_price" or "percentage_drop"
    trigger_type: Mapped[str] = mapped_column(String(32))

    # For target_price: alert when price drops below this GBP value.
    target_price_gbp: Mapped[float | None] = mapped_column(Float, nullable=True)

    # For percentage_drop: alert when price drops by this % from last seen.
    percentage_drop: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Whether this alert is still active.
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    # Timestamp of last notification sent (prevents spam re-alerting).
    last_notified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship(back_populates="alert_rules")
    saved_search: Mapped["SavedSearch"] = relationship(back_populates="alert_rules")
